# Generated by Django 4.1.7 on 2023-04-11 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_blogmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
