# Generated by Django 4.1.7 on 2023-04-18 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0008_feedback'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feedback',
            new_name='Feedbacks',
        ),
    ]
