# Generated by Django 4.1.7 on 2023-04-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0010_remove_profile_is_verified_remove_profile_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
