# Generated by Django 4.1.7 on 2023-04-19 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0011_registration_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='user_type',
        ),
    ]
