# Generated by Django 4.1.7 on 2023-04-28 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0016_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draft',
            name='image',
            field=models.ImageField(upload_to='draft'),
        ),
    ]
