# Generated by Django 4.1.7 on 2023-04-28 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0017_alter_draft_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='draft',
            new_name='drafts',
        ),
    ]
