# Generated by Django 4.1.7 on 2023-04-28 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0018_rename_draft_drafts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drafts',
            name='is_verified',
        ),
    ]
