# Generated by Django 4.1.7 on 2023-05-05 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0019_remove_drafts_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='profile_pic',
            field=models.ImageField(default='default-avatar.bacg1.png', null=True, upload_to='profile'),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
