# Generated by Django 4.1.7 on 2023-05-22 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0022_alter_registration_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
