# Generated by Django 4.1.7 on 2023-05-23 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0024_blogmodel_five_star_counts_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogmodel',
            old_name='five_star_counts',
            new_name='avg_rating',
        ),
        migrations.RemoveField(
            model_name='blogmodel',
            name='four_star_counts',
        ),
        migrations.RemoveField(
            model_name='blogmodel',
            name='one_star_counts',
        ),
        migrations.RemoveField(
            model_name='blogmodel',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='blogmodel',
            name='three_star_counts',
        ),
        migrations.RemoveField(
            model_name='blogmodel',
            name='two_star_counts',
        ),
    ]
