# Generated by Django 4.1.7 on 2023-05-23 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0025_rename_five_star_counts_blogmodel_avg_rating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='blogmodel',
            name='avg_rating',
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='ratings',
            field=models.ManyToManyField(related_name='blogs', to='blogapp.rating'),
        ),
    ]
