# Generated by Django 4.1.7 on 2023-05-23 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogapp', '0026_rating_remove_blogmodel_avg_rating_blogmodel_ratings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='value',
            new_name='rate',
        ),
        migrations.AddField(
            model_name='rating',
            name='title',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='blogapp.blogmodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rating',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
