# Generated by Django 4.1.7 on 2023-05-24 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0027_rename_value_rating_rate_rating_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='ratings',
        ),
        migrations.AlterField(
            model_name='rating',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blogapp.registration'),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='ratings',
            field=models.FloatField(null=True),
        ),
    ]
