# Generated by Django 4.1.7 on 2023-05-25 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0028_remove_blogmodel_ratings_alter_rating_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='ratings',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
